name: Sync Fork

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 时间 1 点执行
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v3
        with:
          ref: main  # 你 fork 的默认分支名字，比如 main 或 master

      - name: Add upstream remote
        run: git remote add upstream https://github.com/mqiancheng/freecloud.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into local main
        run: git merge upstream/main

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
