name: Sync Fork Daily

on:
  schedule:
    - cron: '0 0 * * *'   # 每天UTC时间凌晨0点执行
  workflow_dispatch:       # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork repo
        uses: actions/checkout@v3
        with:
          ref: main  # 如果你的分支名不是main，改成你的分支名

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/mqiancheng/freecloud.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      - name: Push changes to your fork
        env:
          GITHUB_TOKEN: ${{ secrets_
